version: '3.8'
services:
  mysqlsocialwire: #contenedor de mysql
    image: mysql:5.7
    container_name: mysqlsocialwire
    ports:
      - 3307:3306
    volumes:
      - ./mysqlsocialwire:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret.root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - inlazeSicial
  socialwirebackend:
    container_name: socialwirebackend
    image: inlaze/social-wire-backend:0.0.1 #llama la imagen
    tty: true
    restart: always
    ports:
      - 4501:3000 #El puerto de salida API
    environment: #las variable de entorno
      - MYSQL_HOST_DM=mysqlsocialwire
      - MYSQL_PORT_DM=3306
      - MYSQL_DATABASE_NAME_DM=homestead
      - MYSQL_ROOT_USER_DM=root
      - MYSQL_ROOT_PASSWORD_DM=secret.root
      - JWT_SECRET='$prueba'
      - PORT=3000
    depends_on:
      - mysqlsocialwire
    networks:
      - inlazeSicial
networks:
  inlazeSicial:
    driver: bridge
    name: inlazeSicial
volumes:
  mysqlsocialwire:
    name: mysqlsocialwire
